# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 772b117e3eeb2a02bba69aa7ff88386ef44af3ff3f8ae14c4646f80060ea3b7cbd10e518883e757c71f1b81794e18262fd4d6429aa8517f50f83da444eea2dab

test:
  secret_key_base: 4bc77ce1c4675c66a4a0d12060f18622ca8feab7f8ba563a1ba40555600034ee00c9c2318f0fa8f4d84d4eb22c7e12f1692b29e22ede99c7a69f1e86947389c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
